### ISSUE TITLE
Hooking up email to website

### ISSUE THREAD

**Issue by natalie-macpherson** [natalie-macpherson/portfolio#1]
Hi Thomas,

I know you just want to have the css/html done for this part of the project but I am also trying to get my form to hook up to the email setup for my website (for now just my gmail account). I tried it on my live website because github does not support email service (error 405) (I took it off for now) but it does not work. I already got help with setting up the php code and I tried to do an echo but I got nothing back. I am assuming there is something wrong with the php code that is currently on the website but for the life of me I can't figure it out and my boyfriend is not able to see anything either. I was able to set up the php code to open up the apple default mail app but that would defeat the point of what I am trying to do. I hope this makes sense, it's kind of hard for me to explain. 

The php code is here: https://github.com/natalie-macpherson/portfolio/blob/gh-pages/connect.html#L80-L99
The form is here: https://github.com/natalie-macpherson/portfolio/blob/gh-pages/connect.html#L51-L64

@thomasjbradley

**Comment by thomasjbradley** [comment]
The problem that you're likely running into is that PHP doesn't work on GitHub, you need another host to run dynamic backend languages; GitHub only supports static websites.

I've used this before and it works great for getting forms functional; try it out:
http://formspree.io/

**Comment by thomasjbradley** [comment]
As a side note: why use a form at all? It isn't collecting anything specific from the user and lots of studies have shown that users will just avoid forms if they can. Since its a basic e-mail form, its just more user friendly to post your e-mail address that's clickable.

**Comment by natalie-macpherson** [comment]
Ok. I'll do that instead. Thank you for the suggestion.
